import React from 'react';

/**
 * Strategy translation mapping function.
 * NEVER displays raw strategy constants to the organizer.
 */
function translateStrategy(strategy) {
  switch (strategy) {
    case 'absorb_via_buffer':
      return 'Absorbed using a buffer segment downstream.';
    case 'compress_next_sessions':
      return 'Absorbed by trimming upcoming sessions slightly.';
    case 'insert_filler_segment':
      return 'Pushed the full delay onto the rest of the schedule.';
    default:
      return 'Schedule adjusted dynamically.';
  }
}

export default function DelayResultCard({ result, onDismiss }) {
  if (!result) return null;

  const { liveState, script, strategy, enteredMinutes } = result;
  const totalOffset = liveState?.delayOffsetMinutes ?? enteredMinutes;

  const humanStrategy = translateStrategy(strategy);
  const scriptSource = script?.source || 'ai';

  return (
    <div
      className="organizer-card"
      style={{
        marginTop: '1.25rem',
        marginBottom: '1.25rem',
        border: '1px solid var(--organizer-warning)',
        boxShadow: 'var(--shadow-md)',
        backgroundColor: 'rgba(245, 158, 11, 0.05)',
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.85rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <span style={{ fontSize: '1.25rem' }}>⚠️</span>
          <h3 style={{ fontSize: '1.1rem', fontWeight: '700', color: 'var(--organizer-warning)', margin: 0 }}>
            Delay Reported Successfully
          </h3>
        </div>
        {onDismiss && (
          <button
            onClick={onDismiss}
            style={{
              background: 'none',
              border: 'none',
              color: 'var(--organizer-text-muted)',
              fontSize: '1rem',
              cursor: 'pointer',
            }}
          >
            ✕
          </button>
        )}
      </div>

      {/* Delay Metrics */}
      <div
        style={{
          display: 'flex',
          flexWrap: 'wrap',
          gap: '1rem',
          padding: '0.75rem 1rem',
          backgroundColor: 'var(--organizer-surface)',
          borderRadius: 'var(--radius-md)',
          border: '1px solid var(--organizer-border)',
          marginBottom: '1rem',
          fontSize: '0.9rem',
          fontWeight: '600',
        }}
      >
        <div style={{ color: 'var(--organizer-text)' }}>
          ⏱️ This delay: <span style={{ color: 'var(--organizer-warning)' }}>{enteredMinutes} min</span>
        </div>
        <div style={{ color: 'var(--organizer-border)', userSelect: 'none' }}>|</div>
        <div style={{ color: 'var(--organizer-text)' }}>
          📊 Total so far: <span style={{ color: 'var(--organizer-warning)' }}>{totalOffset} min</span>
        </div>
      </div>

      {/* Strategy Description (Translated to Plain English) */}
      <div style={{ marginBottom: '1rem' }}>
        <span
          style={{
            fontSize: '0.75rem',
            fontWeight: '700',
            color: 'var(--organizer-text-muted)',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
            display: 'block',
            marginBottom: '0.25rem',
          }}
        >
          Replanning Strategy Applied
        </span>
        <p
          style={{
            fontSize: '0.95rem',
            fontWeight: '600',
            color: 'var(--organizer-text)',
            margin: 0,
          }}
        >
          💡 {humanStrategy}
        </p>
      </div>

      {/* Generated Filler Script */}
      {script?.content && (
        <div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.35rem' }}>
            <span
              style={{
                fontSize: '0.75rem',
                fontWeight: '700',
                color: 'var(--organizer-text-muted)',
                textTransform: 'uppercase',
                letterSpacing: '0.05em',
              }}
            >
              📜 Generated Stage Filler Script
            </span>
            <span
              style={{
                fontSize: '0.7rem',
                fontWeight: '600',
                padding: '0.15rem 0.45rem',
                borderRadius: 'var(--radius-sm)',
                backgroundColor: scriptSource === 'ai' ? 'rgba(56, 189, 248, 0.15)' : 'var(--organizer-surface-hover)',
                color: scriptSource === 'ai' ? '#38bdf8' : 'var(--organizer-text-secondary)',
                border: '1px solid var(--organizer-border)',
              }}
            >
              {scriptSource === 'ai' ? '✨ Generated by AI' : '📋 Standard Fallback'}
            </span>
          </div>
          <div
            style={{
              backgroundColor: 'var(--organizer-bg)',
              border: '1px solid var(--organizer-border)',
              borderRadius: 'var(--radius-md)',
              padding: '0.85rem 1rem',
              fontSize: '0.875rem',
              lineHeight: '1.6',
              whiteSpace: 'pre-wrap',
              color: 'var(--organizer-text-secondary)',
              maxHeight: '180px',
              overflowY: 'auto',
            }}
          >
            {script.content}
          </div>
        </div>
      )}
    </div>
  );
}
